/**:
  ros__parameters:
    angle_goal_range: 6.0
    astar.adapt_expansion_distance: true
    astar.distance_heuristic_weight: 2.0
    astar.expansion_distance: 0.5
    astar.goal_lat_distance_weight: 5.0
    astar.near_goal_distance: 3.0
    astar.obstacle_distance_weight: 1.75
    astar.only_behind_solutions: false
    astar.search_method: forward
    astar.smoothness_weight: 35.0
    astar.use_back: false
    curve_weight: 0.5
    direction_change_weight: 2.0
    front_overhang: 1.0
    lateral_goal_range: 0.5
    left_overhang: 0.1
    longitudinal_goal_range: 1.0
    max_planning_velocity: 100.0
    max_steer_angle: 0.7
    max_turning_ratio: 0.8
    obstacle_threshold: 100
    path_distance_viz_cap: 5.0
    path_distance_weight: 3.0
    planning_algorithm: astar
    qos_overrides./parameter_events.publisher.depth: 1000
    qos_overrides./parameter_events.publisher.durability: volatile
    qos_overrides./parameter_events.publisher.history: keep_last
    qos_overrides./parameter_events.publisher.reliability: reliable
    rear_overhang: 1.03
    replan_when_course_out: true
    replan_when_obstacle_found: true
    reverse_weight: 0.7
    right_overhang: 0.1
    rrtstar.enable_update: true
    rrtstar.margin: 0.1
    rrtstar.max_planning_time: 150.0
    rrtstar.neighbor_radius: 8.0
    rrtstar.use_informed_sampling: true
    th_arrived_distance_m: 0.5
    th_course_out_distance_m: 1.0
    th_obstacle_time_sec: 0.1
    th_stopped_time_sec: 1.0
    th_stopped_velocity_mps: 0.01
    theta_size: 120
    time_limit: 30000.0
    turning_steps: 2
    update_rate: 10.0
    sampling_end_m: 45.1
    sampling_start_m: 8.0
    sampling_step_m: 10.0
    stuck_replan_time_sec: 3.0
    use_path_distance_cost: true
    use_sim_time: false
    vehicle_height: 2.5
    vehicle_shape_margin_m: 0.3
    waypoints_velocity: 5.0
    wheel_base: 2.74
    wheel_radius: 0.39
    wheel_tread: 1.63
    wheel_width: 0.42
